//"APIName" : "scriptName"
const macbethChars = {
    "ATTENDANTS" : "Attendant",
    "Angus" : "Angus",
    "Banquo" : "Banquo",
    "Caithness" : "Caithness",
    "Doctor1" : "Doctor",
    "Doctor2" : "Doctor",
    "Donalbain" : "Donalbain",
    "Duncan" : "Duncan",
    "Fleance" : "Fleance",
    "Gentlewoman" : "Gentlewoman",
    "Hecate" : "Hecate",
    "LadyMacbeth" : "Lady Macbeth",
    "LadyMacduff" : "Lady Macduff",
    "Lennox" : "Lennox",
    "Lord" : "Lord",
    "MESSENGERS.1" : "Messenger",
    "MESSENGERS.2" : "Messenger",
    "MESSENGERS.3" : "Messenger",
    "MURDERERS" : "Murderer",
    "MURDERERS.1" : "First Murderer",
    "MURDERERS.2" : "Second Murderer",
    "MURDERERS.3" : "Third Murderer",
    "Macbeth" : "Macbeth",
    "Macduff" : "Macduff",
    "MacduffsSon" : "Son",
    "Malcolm" : "Malcolm",
    "Menteith" : "Menteith",
    "OldMan" : "Old Man",
    "Porter" : "Porter",
    "Ross" : "Ross",
    "SERVANTS.X.1" : "Servant",
    "SERVANTS.X.2" : "Servant",
    "SERVANTS.X.3" : "Servant",
    "SERVANTS.X.4" : "Servant",
    "SOLDIERS.Captain" : "Captain",
    "SOLDIERS.MACBETH" : "Macbeth's Soldiers",
    "SOLDIERS.MALCOLM" : "Soldier",
    "SPIRITS.1" : "First Apparition",
    "SPIRITS.2" : "Second Apparition",
    "SPIRITS.3" : "Third Apparition",
    "SPIRITS.KINGS" : "King Apparitions",
    "Seyton" : "Seyton",
    "Siward" : "Siward",
    "WITCHES.1" : "First Witch",
    "WITCHES.2" : "Second Witch",
    "WITCHES.3" : "Third Witch",
    "YoungSiward" : "Young Siward"
}

//"playCode" : "playName"
export const playCodes = {
    "AWW" : "All's Well That Ends Well",
    "Ant" : "Antony and Cleopatra",
    "AYL" : "As You Like It",
    "Err" : "The Comedy of Errors",
    "Cor" : "Coriolanus",
    "Cym" : "Cymbeline",
    "Ham" : "Hamlet",
    "1H4" : "Henry IV, Part 1",
    "2H4" : "Henry IV, Part 2",
    "H5" : "Henry V",
    "1H6" : "Henry VI, Part 1",
    "2H6" : "Henry VI, Part 2",
    "3H6" : "Henry VI, Part 3",
    "H8" : "Henry VIII",
    "JC" : "Julius Caesar",
    "Jn" : "King John",
    "Lr" : "King Lear",
    "LLL" : "Love's Labor's Lost",
    "Mac" : macbethChars,
    "MM" : "Measure for Measure",
    "MV" : "The Merchant of Venice",
    "Wiv" : "The Merry Wives of Windsor",
    "MND" : "A Midsummer Night's Dream",
    "Ado" : "Much Ado About Nothing",
    "Oth" : "Othello",
    "Per" : "Pericles",
    "R2" : "Richard II",
    "R3" : "Richard III",
    "Rom" : "Romeo and Juliet",
    "Shr" : "The Taming of the Shrew",
    "Tmp" : "The Tempest",
    "Tim" : "Timon of Athens",
    "Tit" : "Titus Andronicus",
    "Tro" : "Troilus and Cressida",
    "TN" : "Twelfth Night",
    "TGV" : "Two Gentlemen of Verona",
    "TNK" : "Two Noble Kinsmen",
    "WT" : "The Winter's Tale"
}